export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILURE";
export const ADMIN_AUTH_STATE="ADMIN_AUTH_STATE";
export const THERAPIST_AUTH_STATE="THERAPIST_AUTH_STATE";
export const USER_AUTH_STATE="USER_AUTH_STATE";